[Definition]

actionstart =
actionstop =
actioncheck =

actionban = curl -s \
  -X POST \
  "https://api.cloudflare.com/client/v4/accounts/<cfaccountid>/rules/lists/<cfbanlistid>/items" \
  -H "Authorization: Bearer <cfapitoken>" \
  -H "Content-Type: application/json" \
  --data '[{"ip":"<ip>","comment":"Fail2Ban <name>"}]'

actionunban = ITEM_ID=$(curl -s \
    -H "Authorization: Bearer <cfapitoken>" \
    "https://api.cloudflare.com/client/v4/accounts/<cfaccountid>/rules/lists/<cfbanlistid>/items?search=<ip>" \
  | jq -r '.result[] | select(.ip=="<ip>") | .id'); \
 [ -n "$ITEM_ID" ] && echo "id: $ITEM_ID" && curl -s \
    -X DELETE \
    "https://api.cloudflare.com/client/v4/accounts/<cfaccountid>/rules/lists/<cfbanlistid>/items" \
    -H "Authorization: Bearer <cfapitoken>" \
    -H "Content-Type: application/json" \
    --data '{"items": [{"id": "'$ITEM_ID'" }]}'

[Init]

# If you like to use this action with mailing whois lines, you could use the composite action
# action_cf_mwl predefined in jail.conf, just define in your jail:
#
# action = %(action_cf_mwl)s
# # Your CF account e-mail
# cfemail  = 
# # Your CF API Key
# cfapikey = 

cfapitoken =

cfaccountid =

cfbanlistid = 

cftarget = ip

[Init?family=inet6]
cftarget = ip6
