- id: '1662789977123'
  name: küche normal
  entities:
    light.0x001788010b7e8ea8:
      min_mireds: 222
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: kitchen-hue-1
      supported_features: 47
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      state: 'on'
    light.0x001788010b7e7a8e:
      min_mireds: 222
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: kitchen-hue-2
      supported_features: 47
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      state: 'on'
    light.0x0017880109dae3cd:
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: kitchen-hue-3
      supported_features: 47
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      state: 'on'
    light.kitchen_hue_right:
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      friendly_name: kitchen-hue-right
      supported_features: 47
      state: 'on'
  icon: mdi:light-switch
- id: '1664087988276'
  name: küche gedimmt
  entities:
    light.0x001788010b7e8ea8:
      min_mireds: 222
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: kitchen-hue-1
      supported_features: 47
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      state: 'on'
    light.0x001788010b7e7a8e:
      min_mireds: 222
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: kitchen-hue-2
      supported_features: 47
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      state: 'on'
    light.0x0017880109dae3cd:
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: kitchen-hue-3
      supported_features: 47
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      state: 'on'
    light.kitchen_hue_right:
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: kitchen-hue-right
      supported_features: 47
      color_mode: color_temp
      brightness: 255
      color_temp: 366
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      state: 'on'
  icon: mdi:light-switch
