[hosts]
home ansible_host=192.172.100.20
proxmox ansible_host=proxmox.strieter.dev
backup ansible_host=192.172.100.200

[runners]
bob ansible_host=bob.strieter.dev

[devices]
router ansible_host=router.strieter.eu
