[hosts]
home ansible_host=192.172.100.20
proxmox ansible_host=proxmox.strieter.dev
backup ansible_host=192.172.100.200

[devices]
router ansible_host=router.strieter.eu

# pve ansible_host=pve.strieter.dev #192.172.100.172
