[hosts]
home ansible_host=192.172.100.20
proxmox ansible_host=proxmox.strieter.dev
oc2 ansible_host=192.172.100.172
backup ansible_host=192.172.100.200
home-assistant ansible_host=192.172.100.151

[hypervisors]
oc2
proxmox

[runners]
bob ansible_host=bob.strieter.dev

[devices]
router ansible_host=router.strieter.eu
