roles:
  - name: geerlingguy.docker
    version: 8.0.0
  - name: geerlingguy.pip
    version: 3.1.2
  - name: lae.proxmox
    version: v1.10.1
  - name: borgbase.ansible_role_borgbackup
    version: "v2.0.0"

collections:
  - name: ansible.posix
    version: 2.2.0
  - name: community.general
    version: 13.0.1
  - name: community.docker
    version: 5.2.1
  - name: community.proxmox
    version: 2.0.0
  - name: devsec.hardening
    version: '10.6.0'
  - name: hifis.toolkit
  - name: community.openwrt
    version: 1.5.0
