- name: Ensure proxmoxer is available
  ansible.builtin.package:
    name: python3-proxmoxer
    state: present

- name: Initialize guest VM list
  ansible.builtin.set_fact:
    proxmox_kvm_guests: []

- name: Build guest VM list
  ansible.builtin.set_fact:
    proxmox_kvm_guests: >-
      {{
         proxmox_kvm_guests | default([]) +
          (
            (
              guest_config.host | default('', true) == inventory_hostname and
              guest_config.type | default('kvm') == 'kvm'
            ) | ternary(
              [
                {
                  'inventory_hostname': item,
                  'inventory_hostname_short': hostvars[item].inventory_hostname_short,
                  'kvm': guest_config
                }
              ],
              []
            )
          )
      }}
  loop: "{{ groups['all'] | default([]) }}"
  vars:
    guest_config: "{{ hostvars[item].proxmox | default(hostvars[item].vm | default({})) }}"

- name: Create guest VMs
  community.proxmox.proxmox_kvm:
    api_token_id: "{{ proxmox_api_token_id | mandatory }}"
    api_token_secret: "{{ proxmox_api_token_secret | mandatory }}"
    api_user: "{{ proxmox_api_user | mandatory }}"
    api_host: localhost
    validate_certs: false
    node: "{{ ansible_hostname | mandatory }}"
    vmid: "{{ guest.kvm.id | mandatory }}"
    name: "{{ guest.inventory_hostname_short | mandatory }}"
    agent: true
    protection: true
    autostart: true
    onboot: true
    startup: "{{ guest.kvm.startup | default(omit) }}"
    acpi: true
    kvm: true
    balloon: "{{ guest.kvm.balloon | default(false) }}"
    memory: "{{ guest.kvm.memory | mandatory }}"
    bios: ovmf
    efidisk0:
      storage: "{{ guest.kvm.efi_disk_storage | default('local-lvm') }}"
      format: raw
      efitype: 4m
      pre_enrolled_keys: 1
    boot: order=scsi0;ide0
    sockets: "{{ guest.kvm.sockets | default(1) }}"
    cores: "{{ guest.kvm.cores | mandatory }}"
    cpu: host
    machine: q35
    hotplug: disk,network,usb
    vga: "{{ guest.kvm.vga | default(omit) }}"
    ide:
      ide0: none # local:iso/Fedora-Server-netinst-x86_64-37-1.7.iso,media=cdrom
    scsihw: virtio-scsi-single
    scsi: "{{ guest.kvm.scsi | default(omit) }}"
    net: "{{ guest.kvm.net | default(omit) }}"
    # According to https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu
    # this is experimental. And it currently fails, which is why we handle
    # such devices manually below.
    # hostpci: "{{ guest.kvm.hostpci | default(omit) }}"
    ostype: l26
    watchdog: model=i6300esb,action=reset
  loop: "{{  proxmox_kvm_guests }}"
  loop_control:
    loop_var: guest
    label: "{{ guest.inventory_hostname }} id={{ guest.kvm.id }}"
  notify: Configure guest OS manually
  register: proxmox_vm_guests_created

- name: Add host PCI devices to guest
  ansible.builtin.include_tasks: create-vms-hostpci.yml
  loop: "{{  proxmox_kvm_guests }}"
  loop_control:
    loop_var: guest
    label: "{{ guest.inventory_hostname }} id={{ guest.kvm.id }}"

- name: Add host USB devices to guest
  ansible.builtin.include_tasks: create-vms-usb.yml
  loop: "{{  proxmox_kvm_guests }}"
  loop_control:
    loop_var: guest
    label: "{{ guest.inventory_hostname }} id={{ guest.kvm.id }}"

- name: Install guest OS manually, if a VM was created
  ansible.builtin.meta: flush_handlers
