proxmox:
  host: proxmox
  type: lxc
  id: 3001
  onboot: true
  protection: true
  ostemplate: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  features:
    - nesting=1
    - fuse=1
  password: "{{ vault_proxmox_default_root_password }}"
  ssh_public_key_github_account: FrankStrieter
  memory: 10240
  swap: 20480
  # Re-applying the same network config removes the gateway.
  # Running networkctl reconfigure eth0 helps.
  netif:
    net0: >-
      name=eth0,ip=dhcp,bridge=vmbr0
  disk_volume:
    storage: pve-data
    size: 8
    options:
      mountoptions: discard;noatime
  custom:
    - reason: systemd kernel mounts
      # https://www.enricobassetti.it/2023/05/proxmox-lxc-systemd-and-linux-capabilities/
      key: lxc.cap.drop
      value: sys_rawio
