cloudflare_email: "{{ vault_cloudflare_email}}"
cloudflare_account_id: "{{ vault_cloudflare_account_id }}"
cloudflare_token: "{{ vault_cloudflare_token }}"
cloudflare_zone_id: "{{ vault_cloudflare_zone_id }}"
cloudflare_r2_access_key: "{{vault_cloudflare_r2_access_key}}"
cloudflare_r2_access_secret: "{{vault_cloudflare_r2_access_secret}}"
