[Definition]
failregex = ^.*"RequestPath":"(?:/wp-admin(?:/.*)?|/wp-login\.php|/xmlrpc\.php|/wordpress(?:/.*)?|/phpmyadmin(?:/.*)?|/pma(?:/.*)?|/\.env|/cgi-bin(?:/.*)?|/boaform(?:/.*)?|/manager/html|/actuator(?:/.*)?|/vendor/phpunit(?:/.*)?|/HNAP1/?|/\.git(?:/.*)?|/server-status|/solr(?:/.*)?|/login\.action|/autodiscover/autodiscover\.xml)".*"request_Cf-Connecting-Ip":"<HOST>".*$
ignoreregex =
