- name: Copy templates
  ansible.builtin.import_tasks: copy-templates.yml
  vars:
    directory: ../templates
    target: "{{ otel_root }}"
    should_notify: Restart Open Telemetry # noqa: var-naming[no-reserved]
    files:
      docker-compose.yaml.j2:
        owner: 0
        group: 0
        mode: '640'
      backup.j2:
        mode: '750'
        owner: 0
        group: 0
      restore.j2:
        mode: '750'
        owner: 0
        group: 0

- name: Ensure jq is installed (used for backup script)
  ansible.builtin.package:
    name: jq
    state: present

- name: Restore from backup if requested
  when: restore is defined
  ansible.builtin.import_tasks:
    file: restore.yml
  vars:
    restore_target_dir: "{{ otel_root }}"

- name: Update docker-compose images
  ansible.builtin.import_tasks:
    file: docker-compose-update.yml
  vars:
    directory: "{{ otel_root }}"
    pull: "{{ docker_update is defined }}"
    build: "{{ docker_update is defined }}"
    should_notify: Restart Open Telemetry # noqa: var-naming[no-reserved]

- name: Symlink systemd unit
  ansible.builtin.file:
    state: link
    src: "{{ otel_root }}/{{ ansible_role_name }}.service"
    path: "/etc/systemd/system/{{ ansible_role_name }}.service"
    force: true
  notify: Restart Open Telemetry

- name: Start systemd unit
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ ansible_role_name }}.service"
    daemon_reload: true
  register: otel_started

- name: Symlink backup configuration
  ansible.builtin.file:
    state: link
    src: "{{ otel_root }}/backup.yaml"
    path: "/etc/borgmatic.d/{{ ansible_role_name }}.yaml"

- name: Ensure DNS is registered on router
  ansible.builtin.include_tasks:
    file: router-update-dns.yml
  vars:
    machine_ip: "{{ ansible_facts.default_ipv4.address }}"
    service_url: "{{ item }}"
  with_items:
    - "{{ grafana_domain }}"
    - "{{ prometheus_domain }}"
    - "{{ otel_collector_domain }}"

- name: Set up observability
  ansible.builtin.import_tasks:
    file: setup-observability.yml
  vars:
    directory: "{{ otel_root }}"
